### ISSUE TITLE
Video data

### ISSUE THREAD

**Issue by arturbecker** [Neverblade/intelligent-ik#1]
Hi, thanks for your work and making it available.
I wonder if you also recorded video data to go with the mocap. That way, it could work as a small human pose estimation dataset with VR, which would be unique.

**Comment by Neverblade** [comment]
Hey @arturbecker,

That's a great idea! Unfortunately when we were capturing this dataset we didn't setup video capture to sync up with the mocap. There are a few videos taken for the purposes of presentation, but not enough to put together a meaningful dataset.
